name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update Code and Restart Service
        run: |
          cd ~/ubuntuserver
          git pull origin main
          sudo systemctl restart aicam.service
          sudo systemctl status aicam.service --no-pager